(cl:defpackage quad_msgs-msg
  (:use )
  (:export
   "<CONTROLCOMMAND>"
   "CONTROLCOMMAND"
   "<CONTROLLERFEEDBACK>"
   "CONTROLLERFEEDBACK"
   "<ONBOARDPARAMETER>"
   "ONBOARDPARAMETER"
   "<ONBOARDSTATUS>"
   "ONBOARDSTATUS"
   "<PX4TIMESYNC>"
   "PX4TIMESYNC"
   "<QUADDESIREDSTATE>"
   "QUADDESIREDSTATE"
   "<QUADDESIREDTORQUESANDTHRUST>"
   "QUADDESIREDTORQUESANDTHRUST"
   "<QUADGPIOPWMCTRL>"
   "QUADGPIOPWMCTRL"
   "<QUADREFERENCECOMMAND>"
   "QUADREFERENCECOMMAND"
   "<QUADROTORTHRUSTS>"
   "QUADROTORTHRUSTS"
   "<QUADSTATEESTIMATE>"
   "QUADSTATEESTIMATE"
  ))

