// Generated by gencpp from file px4_test_pkg/Mission.msg
// DO NOT EDIT!


#ifndef PX4_TEST_PKG_MESSAGE_MISSION_H
#define PX4_TEST_PKG_MESSAGE_MISSION_H

#include <ros/service_traits.h>


#include <px4_test_pkg/MissionRequest.h>
#include <px4_test_pkg/MissionResponse.h>


namespace px4_test_pkg
{

struct Mission
{

typedef MissionRequest Request;
typedef MissionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Mission
} // namespace px4_test_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::px4_test_pkg::Mission > {
  static const char* value()
  {
    return "5a500ca8314e489419937af52c2e5ce0";
  }

  static const char* value(const ::px4_test_pkg::Mission&) { return value(); }
};

template<>
struct DataType< ::px4_test_pkg::Mission > {
  static const char* value()
  {
    return "px4_test_pkg/Mission";
  }

  static const char* value(const ::px4_test_pkg::Mission&) { return value(); }
};


// service_traits::MD5Sum< ::px4_test_pkg::MissionRequest> should match
// service_traits::MD5Sum< ::px4_test_pkg::Mission >
template<>
struct MD5Sum< ::px4_test_pkg::MissionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::px4_test_pkg::Mission >::value();
  }
  static const char* value(const ::px4_test_pkg::MissionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_test_pkg::MissionRequest> should match
// service_traits::DataType< ::px4_test_pkg::Mission >
template<>
struct DataType< ::px4_test_pkg::MissionRequest>
{
  static const char* value()
  {
    return DataType< ::px4_test_pkg::Mission >::value();
  }
  static const char* value(const ::px4_test_pkg::MissionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::px4_test_pkg::MissionResponse> should match
// service_traits::MD5Sum< ::px4_test_pkg::Mission >
template<>
struct MD5Sum< ::px4_test_pkg::MissionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::px4_test_pkg::Mission >::value();
  }
  static const char* value(const ::px4_test_pkg::MissionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::px4_test_pkg::MissionResponse> should match
// service_traits::DataType< ::px4_test_pkg::Mission >
template<>
struct DataType< ::px4_test_pkg::MissionResponse>
{
  static const char* value()
  {
    return DataType< ::px4_test_pkg::Mission >::value();
  }
  static const char* value(const ::px4_test_pkg::MissionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PX4_TEST_PKG_MESSAGE_MISSION_H
