// Generated by gencpp from file px4_test_pkg/MissionResponse.msg
// DO NOT EDIT!


#ifndef PX4_TEST_PKG_MESSAGE_MISSIONRESPONSE_H
#define PX4_TEST_PKG_MESSAGE_MISSIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_test_pkg
{
template <class ContainerAllocator>
struct MissionResponse_
{
  typedef MissionResponse_<ContainerAllocator> Type;

  MissionResponse_()
    : success(false)
    , message()  {
    }
  MissionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::px4_test_pkg::MissionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_test_pkg::MissionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MissionResponse_

typedef ::px4_test_pkg::MissionResponse_<std::allocator<void> > MissionResponse;

typedef boost::shared_ptr< ::px4_test_pkg::MissionResponse > MissionResponsePtr;
typedef boost::shared_ptr< ::px4_test_pkg::MissionResponse const> MissionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_test_pkg::MissionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_test_pkg::MissionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px4_test_pkg::MissionResponse_<ContainerAllocator1> & lhs, const ::px4_test_pkg::MissionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px4_test_pkg::MissionResponse_<ContainerAllocator1> & lhs, const ::px4_test_pkg::MissionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px4_test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::px4_test_pkg::MissionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_test_pkg::MissionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_test_pkg::MissionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_test_pkg::MissionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_test_pkg::MissionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_test_pkg::MissionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_test_pkg::MissionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::px4_test_pkg::MissionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_test_pkg::MissionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_test_pkg/MissionResponse";
  }

  static const char* value(const ::px4_test_pkg::MissionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_test_pkg::MissionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
;
  }

  static const char* value(const ::px4_test_pkg::MissionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_test_pkg::MissionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_test_pkg::MissionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_test_pkg::MissionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_TEST_PKG_MESSAGE_MISSIONRESPONSE_H
