// Generated by gencpp from file quad_msgs/ControlCommand.msg
// DO NOT EDIT!


#ifndef QUAD_MSGS_MESSAGE_CONTROLCOMMAND_H
#define QUAD_MSGS_MESSAGE_CONTROLCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace quad_msgs
{
template <class ContainerAllocator>
struct ControlCommand_
{
  typedef ControlCommand_<ContainerAllocator> Type;

  ControlCommand_()
    : header()
    , control_mode(0)
    , off(false)
    , execution_time()
    , orientation()
    , bodyrates()
    , angular_accelerations()
    , thrust(0.0)
    , mot_throttle()
    , rotor_thrust()  {
      mot_throttle.assign(0.0);

      rotor_thrust.assign(0.0);
  }
  ControlCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , control_mode(0)
    , off(false)
    , execution_time()
    , orientation(_alloc)
    , bodyrates(_alloc)
    , angular_accelerations(_alloc)
    , thrust(0.0)
    , mot_throttle()
    , rotor_thrust()  {
  (void)_alloc;
      mot_throttle.assign(0.0);

      rotor_thrust.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _control_mode_type;
  _control_mode_type control_mode;

   typedef uint8_t _off_type;
  _off_type off;

   typedef ros::Time _execution_time_type;
  _execution_time_type execution_time;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _bodyrates_type;
  _bodyrates_type bodyrates;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_accelerations_type;
  _angular_accelerations_type angular_accelerations;

   typedef double _thrust_type;
  _thrust_type thrust;

   typedef boost::array<double, 4>  _mot_throttle_type;
  _mot_throttle_type mot_throttle;

   typedef boost::array<double, 4>  _rotor_thrust_type;
  _rotor_thrust_type rotor_thrust;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(NONE)
  #undef NONE
#endif
#if defined(_WIN32) && defined(ANGLE)
  #undef ANGLE
#endif
#if defined(_WIN32) && defined(ANGLERATE)
  #undef ANGLERATE
#endif
#if defined(_WIN32) && defined(ROTTHROTTLE)
  #undef ROTTHROTTLE
#endif

  enum {
    NONE = 0u,
    ANGLE = 1u,
    ANGLERATE = 2u,
    ROTTHROTTLE = 3u,
  };


  typedef boost::shared_ptr< ::quad_msgs::ControlCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quad_msgs::ControlCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ControlCommand_

typedef ::quad_msgs::ControlCommand_<std::allocator<void> > ControlCommand;

typedef boost::shared_ptr< ::quad_msgs::ControlCommand > ControlCommandPtr;
typedef boost::shared_ptr< ::quad_msgs::ControlCommand const> ControlCommandConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quad_msgs::ControlCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quad_msgs::ControlCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quad_msgs::ControlCommand_<ContainerAllocator1> & lhs, const ::quad_msgs::ControlCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.control_mode == rhs.control_mode &&
    lhs.off == rhs.off &&
    lhs.execution_time == rhs.execution_time &&
    lhs.orientation == rhs.orientation &&
    lhs.bodyrates == rhs.bodyrates &&
    lhs.angular_accelerations == rhs.angular_accelerations &&
    lhs.thrust == rhs.thrust &&
    lhs.mot_throttle == rhs.mot_throttle &&
    lhs.rotor_thrust == rhs.rotor_thrust;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quad_msgs::ControlCommand_<ContainerAllocator1> & lhs, const ::quad_msgs::ControlCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quad_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::quad_msgs::ControlCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quad_msgs::ControlCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quad_msgs::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quad_msgs::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quad_msgs::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quad_msgs::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quad_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4ea83396796aba2c3fbc0dae6c13858";
  }

  static const char* value(const ::quad_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4ea83396796aba2ULL;
  static const uint64_t static_value2 = 0xc3fbc0dae6c13858ULL;
};

template<class ContainerAllocator>
struct DataType< ::quad_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quad_msgs/ControlCommand";
  }

  static const char* value(const ::quad_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quad_msgs::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Control Command\n"
"# This message is sent to a low level controller on the quadrotor\n"
"\n"
"# control mode enums\n"
"uint8 NONE=0\n"
"uint8 ANGLE=1\n"
"uint8 ANGLERATE=2\n"
"uint8 ROTTHROTTLE=3\n"
"\n"
"\n"
"Header header\n"
"\n"
"# Control mode as defined above\n"
"uint8 control_mode\n"
"\n"
"# Flag whether controller was set to OFF\n"
"bool off\n"
"\n"
"# Time at which this command should be executed\n"
"time execution_time\n"
"\n"
"# Orientation of the body frame with respect to the world frame [-]\n"
"geometry_msgs/Quaternion orientation\n"
"\n"
"# Body rates in body frame [rad/s]\n"
"# Note that in ANGLE mode the x-y-bodyrates are only feed forward terms computed from a reference trajectory\n"
"# Also in ANGLE mode, the z-bodyrate has to be from feedback control\n"
"geometry_msgs/Vector3 bodyrates\n"
"\n"
"# Angular accelerations in body frame [rad/s^2]\n"
"geometry_msgs/Vector3 angular_accelerations\n"
"\n"
"# Collective mass normalized thrust [m/s^2]\n"
"float64 thrust\n"
"\n"
"# Single rotor throttle [0-2000]\n"
"float64[4] mot_throttle\n"
"\n"
"# Single rotor thrust\n"
"float64[4] rotor_thrust\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quad_msgs::ControlCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quad_msgs::ControlCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.control_mode);
      stream.next(m.off);
      stream.next(m.execution_time);
      stream.next(m.orientation);
      stream.next(m.bodyrates);
      stream.next(m.angular_accelerations);
      stream.next(m.thrust);
      stream.next(m.mot_throttle);
      stream.next(m.rotor_thrust);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quad_msgs::ControlCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quad_msgs::ControlCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "control_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_mode);
    s << indent << "off: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.off);
    s << indent << "execution_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.execution_time);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "bodyrates: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.bodyrates);
    s << indent << "angular_accelerations: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_accelerations);
    s << indent << "thrust: ";
    Printer<double>::stream(s, indent + "  ", v.thrust);
    s << indent << "mot_throttle[]" << std::endl;
    for (size_t i = 0; i < v.mot_throttle.size(); ++i)
    {
      s << indent << "  mot_throttle[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.mot_throttle[i]);
    }
    s << indent << "rotor_thrust[]" << std::endl;
    for (size_t i = 0; i < v.rotor_thrust.size(); ++i)
    {
      s << indent << "  rotor_thrust[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.rotor_thrust[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUAD_MSGS_MESSAGE_CONTROLCOMMAND_H
