// Generated by gencpp from file quad_msgs/QuadReferenceCommand.msg
// DO NOT EDIT!


#ifndef QUAD_MSGS_MESSAGE_QUADREFERENCECOMMAND_H
#define QUAD_MSGS_MESSAGE_QUADREFERENCECOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace quad_msgs
{
template <class ContainerAllocator>
struct QuadReferenceCommand_
{
  typedef QuadReferenceCommand_<ContainerAllocator> Type;

  QuadReferenceCommand_()
    : header()
    , estimator_id(0)
    , position()
    , velocity()
    , acceleration()  {
    }
  QuadReferenceCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , estimator_id(0)
    , position(_alloc)
    , velocity(_alloc)
    , acceleration(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _estimator_id_type;
  _estimator_id_type estimator_id;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;





  typedef boost::shared_ptr< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> const> ConstPtr;

}; // struct QuadReferenceCommand_

typedef ::quad_msgs::QuadReferenceCommand_<std::allocator<void> > QuadReferenceCommand;

typedef boost::shared_ptr< ::quad_msgs::QuadReferenceCommand > QuadReferenceCommandPtr;
typedef boost::shared_ptr< ::quad_msgs::QuadReferenceCommand const> QuadReferenceCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quad_msgs::QuadReferenceCommand_<ContainerAllocator1> & lhs, const ::quad_msgs::QuadReferenceCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.estimator_id == rhs.estimator_id &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.acceleration == rhs.acceleration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quad_msgs::QuadReferenceCommand_<ContainerAllocator1> & lhs, const ::quad_msgs::QuadReferenceCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quad_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2274d8738fcb1166ada5fd1b8bc73cc2";
  }

  static const char* value(const ::quad_msgs::QuadReferenceCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2274d8738fcb1166ULL;
  static const uint64_t static_value2 = 0xada5fd1b8bc73cc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quad_msgs/QuadReferenceCommand";
  }

  static const char* value(const ::quad_msgs::QuadReferenceCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Quadrotor outerloop reference\n"
"# This Message is published by a controller\n"
"\n"
"Header header\n"
"\n"
"#\n"
"int8 estimator_id\n"
"\n"
"# 3D position in world frame [m]\n"
"geometry_msgs/Vector3 position\n"
"\n"
"# 3D velocity in world frame [m/s]\n"
"geometry_msgs/Vector3 velocity\n"
"\n"
"# Acc command\n"
"geometry_msgs/Vector3 acceleration\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quad_msgs::QuadReferenceCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.estimator_id);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadReferenceCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quad_msgs::QuadReferenceCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quad_msgs::QuadReferenceCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "estimator_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.estimator_id);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUAD_MSGS_MESSAGE_QUADREFERENCECOMMAND_H
