// Generated by gencpp from file quad_msgs/QuadRotorThrusts.msg
// DO NOT EDIT!


#ifndef QUAD_MSGS_MESSAGE_QUADROTORTHRUSTS_H
#define QUAD_MSGS_MESSAGE_QUADROTORTHRUSTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace quad_msgs
{
template <class ContainerAllocator>
struct QuadRotorThrusts_
{
  typedef QuadRotorThrusts_<ContainerAllocator> Type;

  QuadRotorThrusts_()
    : header()
    , thrust_1(0.0)
    , thrust_2(0.0)
    , thrust_3(0.0)
    , thrust_4(0.0)  {
    }
  QuadRotorThrusts_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , thrust_1(0.0)
    , thrust_2(0.0)
    , thrust_3(0.0)
    , thrust_4(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _thrust_1_type;
  _thrust_1_type thrust_1;

   typedef double _thrust_2_type;
  _thrust_2_type thrust_2;

   typedef double _thrust_3_type;
  _thrust_3_type thrust_3;

   typedef double _thrust_4_type;
  _thrust_4_type thrust_4;





  typedef boost::shared_ptr< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> const> ConstPtr;

}; // struct QuadRotorThrusts_

typedef ::quad_msgs::QuadRotorThrusts_<std::allocator<void> > QuadRotorThrusts;

typedef boost::shared_ptr< ::quad_msgs::QuadRotorThrusts > QuadRotorThrustsPtr;
typedef boost::shared_ptr< ::quad_msgs::QuadRotorThrusts const> QuadRotorThrustsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quad_msgs::QuadRotorThrusts_<ContainerAllocator1> & lhs, const ::quad_msgs::QuadRotorThrusts_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.thrust_1 == rhs.thrust_1 &&
    lhs.thrust_2 == rhs.thrust_2 &&
    lhs.thrust_3 == rhs.thrust_3 &&
    lhs.thrust_4 == rhs.thrust_4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quad_msgs::QuadRotorThrusts_<ContainerAllocator1> & lhs, const ::quad_msgs::QuadRotorThrusts_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quad_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "971e125a0994b8a82a3a4740294147b2";
  }

  static const char* value(const ::quad_msgs::QuadRotorThrusts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x971e125a0994b8a8ULL;
  static const uint64_t static_value2 = 0x2a3a4740294147b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quad_msgs/QuadRotorThrusts";
  }

  static const char* value(const ::quad_msgs::QuadRotorThrusts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Single rotor thrusts of a quadrotor\n"
"# This message is received from onboard (the actually applied rotor thrusts)\n"
"\n"
"Header header\n"
"\n"
"# Single rotor thrusts [N]\n"
"float64 thrust_1\n"
"float64 thrust_2\n"
"float64 thrust_3\n"
"float64 thrust_4\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::quad_msgs::QuadRotorThrusts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.thrust_1);
      stream.next(m.thrust_2);
      stream.next(m.thrust_3);
      stream.next(m.thrust_4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadRotorThrusts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quad_msgs::QuadRotorThrusts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quad_msgs::QuadRotorThrusts_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "thrust_1: ";
    Printer<double>::stream(s, indent + "  ", v.thrust_1);
    s << indent << "thrust_2: ";
    Printer<double>::stream(s, indent + "  ", v.thrust_2);
    s << indent << "thrust_3: ";
    Printer<double>::stream(s, indent + "  ", v.thrust_3);
    s << indent << "thrust_4: ";
    Printer<double>::stream(s, indent + "  ", v.thrust_4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUAD_MSGS_MESSAGE_QUADROTORTHRUSTS_H
